### ISSUE TITLE
update data to permendagri no 56 tahun 2015

### ISSUE THREAD

**Issue by cahyadsn** [cahyadsn/daerah#1]
data permendagri no 39 tahun 2015 sudah diganti dan tidak berlaku sejak dikeluarkannya permendagri no 56 tahun 2015

**Comment by diazsasak** [comment]
Apakah data ini sudah diperbaharui ke permendagri no 56 tahun 2015 Pak ?
soalnya di tab code di repo ini masih tertera data permendagri no 39 tahun 2015

**Comment by cahyadsn** [comment]
data permendagri no 56 tahun 2015 ada di http://github.com/cahyadsn/wilayah
