### ISSUE TITLE
Data yg tersimpan bukan nama prov melainkan id

### ISSUE THREAD

**Issue by rendyartg** [cahyadsn/daerah#3]
Data yg tersimpan bukan nama prov melainkan id

**Comment by cahyadsn** [comment]
Jika yng di simpan nama provinsi maka akan terjadi redundancy data, jadi cukup disimpan relation id-ya saja

**Comment by rendyartg** [comment]
Bagaimana menyimpan nama prov kab kec kel
Tp id yg tersimpan
Sulit untuk menampilkan data klo yg tersimpan id aja
