### ISSUE TITLE
[ask] Update data tahun 2020

### ISSUE THREAD

**Issue by pandyandi** [cahyadsn/daerah#5]
mas cahya mau nanya, untuk file sql di [sini](https://github.com/cahyadsn/daerah/blob/master/db_daerah.sql) apakah sudah ada lagi update terbarunya untuk tahun 2020?

**Comment by cahyadsn** [comment]
untuk data dan aplikasi terbaru silakan mengacu ke https://github.com/cahyadsn/wilayah

**Comment by pandyandi** [comment]
udah saya cek ke link tersebut tetapi tidak ada sql yang berelasi untuk table kelurahan -> kecamatan -> kota -> provinsi seperti pada db_daerah.sql di versi sebelumnya

**Comment by cahyadsn** [comment]
sudah saya tambahkan query untuk konversi data dari db wilayah_2020 ke db daerah

**Comment by pandyandi** [comment]
maaf mas masih ada error saat menginputkan datanya


-- TRUNCATE TABLE kabupaten;
INSERT INTO kabupaten (id_kab, id_prov, nama, id_jenis)
SELECT 
    REPLACE(kode,'.') AS id_kab, 
    LEFT(kode,2) AS id_prov, 
    nama, 
    IF(SUBSTR(kode,4,1)='7',2,1) AS id_jenis
FROM wilayah_2020
WHERE LENGTH(kode)=5
ORDER BY kode

> 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS id_kab, 
      LEFT(kode,2) AS id_prov, 
      nama, 
      IF(SUBSTR(kode,4,1' at line 3
	  

	  
-- TRUNCATE TABLE kecamatan;
INSERT INTO kecamatan (id_kec, id_kab, nama)
SELECT 
    REPLACE(kode,'.') AS id_kec, 
    REPLACE(LEFT(kode,5),'.') AS id_kab, 
    nama
FROM wilayah_2020
WHERE LENGTH(kode)=8
ORDER BY kode

> 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS id_kec, 
      REPLACE(LEFT(kode,5),'.') AS id_kab, 
      nama
  FROM wilayah' at line 3
  


-- TRUNCATE TABLE kelurahan;
INSERT INTO kelurahan (id_kel, id_kec, nama, id_jenis)
SELECT 
    REPLACE(kode,'.') AS id_kel, 
    LEFT(kode,8) AS id_kec, 
    nama, 
    IF(SUBSTR(kode,10,1)='2',3,4) AS id_jenis
FROM wilayah_2020
WHERE LENGTH(kode)=13
ORDER BY kode

> 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS id_kel, 
      LEFT(kode,8) AS id_kec, 
      nama, 
      IF(SUBSTR(kode,10,1' at line 3

**Comment by cahyadsn** [comment]
dari REPLACE(kode,'.') menjadi REPLACE(kode,',','') ... kurang satu parameter

**Comment by pandyandi** [comment]
well done mas cahya, sudah tidak ada error, thanks so much!
