### ISSUE TITLE
Replace kurang satu parameter

### ISSUE THREAD

**Issue by prasetyo-jeanu** [cahyadsn/daerah#6]
`REPLACE(LEFT(kode,5),'.','**XXX**') AS id_kab, `

bagian XXX harus diisi apa ?

> 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS id_kab, 
      nama as nama
  FROM wilayah_2020
  WHERE LENGTH(kode)=8
  ORDER ' at line 5

**Comment by cahyadsn** [comment]
sudah di patch dengan perbaikan di query create table kecamatan dan penambahan di query create table kelurahan
